# Generated by Django 5.2.11 on 2026-02-14 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Export",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("csv", "CSV File"),
                            ("excel", "Excel File"),
                            ("json", "JSON File"),
                            ("pdf_report", "PDF Report"),
                            ("chart_png", "Chart PNG"),
                            ("chart_html", "Interactive Chart HTML"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "exports",
                "ordering": ["-created_at"],
            },
        ),
    ]
