[pytest]
DJANGO_SETTINGS_MODULE = analyticore_api.settings
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths =
    tests
    users
    projects
    analysis
    data_ingestion
    exports
    pipelines
    api_integrations
