# Generated by Django 5.2.11 on 2026-02-14 13:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("file_upload", "File Upload"),
                            ("database", "Database Connection"),
                            ("api", "API Integration"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("uploaded", "Data Uploaded"),
                            ("profiled", "Data Profiled"),
                            ("analyzed", "AI Analyzed"),
                            ("transformed", "Transformed"),
                            ("completed", "Completed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("processed_file_path", models.CharField(blank=True, max_length=500)),
                ("row_count", models.IntegerField(blank=True, null=True)),
                ("column_count", models.IntegerField(blank=True, null=True)),
                ("statistics", models.JSONField(blank=True, default=dict)),
                ("ai_recommendations", models.JSONField(blank=True, default=list)),
                ("applied_transformations", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "projects",
                "ordering": ["-created_at"],
            },
        ),
    ]
