# Generated by Django 5.2.11 on 2026-02-14 18:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("projects", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledPipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schedule_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("custom", "Custom Cron"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "hour",
                    models.IntegerField(default=0, help_text="Hour to run (0-23)"),
                ),
                (
                    "minute",
                    models.IntegerField(default=0, help_text="Minute to run (0-59)"),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        default="*",
                        help_text="Day of week (0-6 or mon-sun)",
                        max_length=20,
                    ),
                ),
                (
                    "day_of_month",
                    models.CharField(
                        default="*", help_text="Day of month (1-31)", max_length=20
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        help_text="Custom cron: minute hour day month weekday",
                        max_length=100,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("refresh_data", "Refresh Data from Source"),
                            ("run_analysis", "Run Statistical Analysis"),
                            ("apply_cleaning", "Apply Data Cleaning Rules"),
                            ("export_data", "Export Data"),
                            (
                                "full_pipeline",
                                "Full Pipeline (Refresh + Analysis + Export)",
                            ),
                        ],
                        default="run_analysis",
                        max_length=30,
                    ),
                ),
                (
                    "pipeline_config",
                    models.JSONField(
                        default=dict, help_text="Additional pipeline configuration"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("run_count", models.IntegerField(default=0)),
                ("consecutive_failures", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "celery_task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_pipeline",
                        to="django_celery_beat.periodictask",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_pipelines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "scheduled_pipelines",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        default="scheduled",
                        help_text="scheduled or manual",
                        max_length=50,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("rows_processed", models.IntegerField(default=0)),
                ("transformations_applied", models.IntegerField(default=0)),
                ("output_file", models.CharField(blank=True, max_length=500)),
                ("logs", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "scheduled_pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="pipelines.scheduledpipeline",
                    ),
                ),
            ],
            options={
                "db_table": "pipeline_runs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="scheduledpipeline",
            index=models.Index(
                fields=["user", "is_active"], name="scheduled_p_user_id_157afe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledpipeline",
            index=models.Index(
                fields=["project", "is_active"], name="scheduled_p_project_34172e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledpipeline",
            index=models.Index(
                fields=["next_run"], name="scheduled_p_next_ru_df9240_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["scheduled_pipeline", "-started_at"],
                name="pipeline_ru_schedul_fbc237_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(fields=["status"], name="pipeline_ru_status_2854f1_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["started_at"], name="pipeline_ru_started_ab0c06_idx"
            ),
        ),
    ]
