# Generated by Django 5.2.11 on 2026-02-14 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("recommendations", models.JSONField(default=list)),
                ("statistics", models.JSONField(default=dict)),
                ("change_log", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "analysis_runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransformationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("step_name", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=100)),
                ("target", models.CharField(max_length=255)),
                ("reason", models.TextField()),
                ("impact", models.JSONField(default=dict)),
                ("confidence", models.FloatField()),
                ("reversible", models.BooleanField(default=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transformations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "transformation_logs",
                "ordering": ["-applied_at"],
            },
        ),
    ]
