# Generated by Django 5.2.11 on 2026-03-15 14:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
        ("projects", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pipeline_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("ingestion", "Data Ingestion"),
                            ("profiling", "Data Profiling"),
                            ("cleaning", "Data Cleaning"),
                            ("transformation", "Transformation"),
                            ("statistics", "Statistical Analysis"),
                            ("correlation", "Correlation Analysis"),
                            ("insights", "AI Insights"),
                            ("visualization", "Visualization"),
                            ("summary", "Executive Summary"),
                        ],
                        default="ingestion",
                        max_length=30,
                    ),
                ),
                ("progress_percent", models.IntegerField(default=0)),
                ("cancel_requested", models.BooleanField(default=False)),
                ("pause_requested", models.BooleanField(default=False)),
                ("stages_completed", models.JSONField(default=list)),
                ("current_stage_data", models.JSONField(default=dict)),
                ("final_results", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("llm_enabled", models.BooleanField(default=True)),
                ("llm_insights", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_runs",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pipeline_progress",
                "ordering": ["-created_at"],
            },
        ),
    ]
