# Generated by Django 5.2.11 on 2026-02-14 14:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("file", "File Upload"),
                            ("mysql", "MySQL Database"),
                            ("postgresql", "PostgreSQL Database"),
                            ("api", "REST API"),
                            ("csv_url", "CSV URL"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "connection_details",
                    models.JSONField(
                        default=dict, help_text="Encrypted connection details"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "data_sources",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_file", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("has_header", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cleaned", "Cleaned"),
                            ("transformed", "Transformed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("columns", models.JSONField(blank=True, null=True)),
                ("row_count", models.PositiveIntegerField(blank=True, null=True)),
                ("preview_data", models.JSONField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cleaned_file",
                    models.FileField(
                        blank=True, null=True, upload_to="cleaned/%Y/%m/%d/"
                    ),
                ),
                ("cleaning_rules", models.JSONField(blank=True, null=True)),
                ("cleaning_stats", models.JSONField(blank=True, null=True)),
                ("cleaned_at", models.DateTimeField(blank=True, null=True)),
                ("is_cleaned_version", models.BooleanField(default=False)),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="data_ingestion.datasource",
                    ),
                ),
                (
                    "original_upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cleaned_versions",
                        to="data_ingestion.dataupload",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "data_uploads",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(
                fields=["user", "source_type"], name="data_source_user_id_849242_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataupload",
            index=models.Index(fields=["user"], name="data_upload_user_id_71dcdb_idx"),
        ),
        migrations.AddIndex(
            model_name="dataupload",
            index=models.Index(fields=["status"], name="data_upload_status_8301f7_idx"),
        ),
        migrations.AddIndex(
            model_name="dataupload",
            index=models.Index(
                fields=["uploaded_at"], name="data_upload_uploade_5f80ba_idx"
            ),
        ),
    ]
