# Generated by Django 5.2.11 on 2026-02-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('file', 'File Upload'), ('mysql', 'MySQL Database'), ('postgresql', 'PostgreSQL Database'), ('google_sheets', 'Google Sheets'), ('api', 'REST API'), ('csv_url', 'CSV URL')], max_length=20),
        ),
    ]
