# Generated by Django 5.2.11 on 2026-02-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_notification_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="email_on_pipeline_complete",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="email_on_pipeline_failed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="push_on_pipeline_complete",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="push_on_pipeline_failed",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("analysis_complete", "Analysis Complete"),
                    ("data_issues", "Data Issues Found"),
                    ("export_ready", "Export Ready"),
                    ("upload_complete", "Upload Complete"),
                    ("project_created", "Project Created"),
                    ("transformation_applied", "Transformation Applied"),
                    ("pipeline_complete", "Pipeline Complete"),
                    ("pipeline_failed", "Pipeline Failed"),
                    ("system", "System Notification"),
                ],
                max_length=30,
            ),
        ),
    ]
