# Generated by Django 5.2.11 on 2026-02-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_notification_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="related_object_type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
