# Generated by Django 5.2.11 on 2026-02-14 20:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_notificationpreference_email_on_pipeline_complete_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("analysis_complete", "Analysis Complete"),
                    ("data_issues", "Data Issues Found"),
                    ("export_ready", "Export Ready"),
                    ("upload_complete", "Upload Complete"),
                    ("project_created", "Project Created"),
                    ("transformation_applied", "Transformation Applied"),
                    ("pipeline_complete", "Pipeline Complete"),
                    ("pipeline_failed", "Pipeline Failed"),
                    ("system", "System Notification"),
                    ("system_alert", "System Alert"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="AdminAlertSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error_rate_threshold",
                    models.FloatField(
                        default=5.0,
                        help_text="Alert when error rate exceeds this percentage",
                    ),
                ),
                (
                    "db_response_threshold_ms",
                    models.IntegerField(
                        default=500,
                        help_text="Alert when DB response exceeds this (milliseconds)",
                    ),
                ),
                (
                    "max_errors_24h",
                    models.IntegerField(
                        default=10,
                        help_text="Alert when errors in 24h exceed this count",
                    ),
                ),
                ("alert_emails_enabled", models.BooleanField(default=True)),
                ("daily_summary_enabled", models.BooleanField(default=True)),
                (
                    "additional_recipients",
                    models.TextField(
                        blank=True,
                        help_text="Additional email addresses (comma-separated)",
                    ),
                ),
                (
                    "health_check_interval_minutes",
                    models.IntegerField(
                        default=15, help_text="How often to run health checks"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert Settings",
                "verbose_name_plural": "Alert Settings",
                "db_table": "admin_alert_settings",
            },
        ),
        migrations.CreateModel(
            name="UserSecuritySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("two_factor_enabled", models.BooleanField(default=False)),
                (
                    "two_factor_method",
                    models.CharField(
                        choices=[("email", "Email OTP"), ("disabled", "Disabled")],
                        default="disabled",
                        max_length=20,
                    ),
                ),
                (
                    "password_changed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("password_expires_at", models.DateTimeField(blank=True, null=True)),
                ("force_password_change", models.BooleanField(default=False)),
                ("failed_login_attempts", models.IntegerField(default=0)),
                ("lockout_until", models.DateTimeField(blank=True, null=True)),
                ("last_failed_login", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_security_settings",
            },
        ),
        migrations.CreateModel(
            name="PasswordHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password_hash", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "password_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="password_hi_user_id_f4f4ce_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "password_reset_tokens",
                "indexes": [
                    models.Index(fields=["token"], name="password_re_token_060a1f_idx"),
                    models.Index(
                        fields=["user", "is_used"],
                        name="password_re_user_id_cd37a3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_success", "Successful Login"),
                            ("login_failed", "Failed Login"),
                            ("logout", "Logout"),
                            ("password_change", "Password Changed"),
                            ("password_reset_request", "Password Reset Requested"),
                            ("password_reset_complete", "Password Reset Completed"),
                            ("2fa_enabled", "2FA Enabled"),
                            ("2fa_disabled", "2FA Disabled"),
                            ("2fa_success", "2FA Verification Success"),
                            ("2fa_failed", "2FA Verification Failed"),
                            ("account_locked", "Account Locked"),
                            ("account_unlocked", "Account Unlocked"),
                            ("settings_changed", "Security Settings Changed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "security_audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "event_type"],
                        name="security_au_user_id_f90dbf_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="security_au_created_fc6824_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TwoFactorOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "otp_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("code", models.CharField(max_length=6)),
                ("code_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("attempts", models.IntegerField(default=0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "two_factor_otp",
                "indexes": [
                    models.Index(
                        fields=["user", "is_used"],
                        name="two_factor__user_id_3d3174_idx",
                    ),
                    models.Index(
                        fields=["otp_id"], name="two_factor__otp_id_a303e3_idx"
                    ),
                ],
            },
        ),
    ]
